name: Deploy Django App with Docker on Apache

on:
  push:
    branches: [django]  # Trigger only on this branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Set up SSH Agent
      uses: webfactory/ssh-agent@v0.8.0
      with:
        ssh-private-key: ${{ secrets.VPS_SSH_KEY }}

    - name: Copy files to VPS
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} "mkdir -p ~/documentintelligence-django-new"
        scp -r . ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:~/documentintelligence-django-new

    - name: Build & Run Docker container on VPS
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << EOF
          export DB_USER="$DB_USER"
          export DB_PASSWORD="patelyash1234"
          export DB_HOST="69.62.78.167"
          export DB_PORT="5432"
          export DB_NAME="doc_db"
          export DATABASE_URL="postgresql://postgres:patelyash1234@69.62.78.167:5432/doc_db"

          export STRIPE_PUBLIC_KEY="${{ secrets.STRIPE_PUBLIC_KEY }}"
          export STRIPE_SECRET_KEY="${{ secrets.STRIPE_SECRET_KEY }}"
          export STRIPE_WEBHOOK_SECRECT="${{ secrets.STRIPE_WEBHOOK_SECRECT }}"

          export GROQ_API_KEY="${{ secrets.GROQ_API_KEY }}"

          export DJANGO_SUPERUSER_USERNAME="${{ secrets.DJANGO_SUPERUSER_USERNAME }}"
          export DJANGO_SUPERUSER_EMAIL="${{ secrets.DJANGO_SUPERUSER_EMAIL }}"
          export DJANGO_SUPERUSER_PASSWORD="${{ secrets.DJANGO_SUPERUSER_PASSWORD }}"


          cd ~/documentintelligence-django-new
          docker stop documentintelligence-django-new || true
          docker rm documentintelligence-django-new || true

          docker build -t documentintelligence-django-new .

          docker run -d -p 8003:8003 --name documentintelligence-django-new \
            -v /root/documentintelligence-django-new/staticfiles:/app/staticfiles \
            -e DB_USER="postgres" \
            -e DB_PASSWORD="patelyash1234" \
            -e DB_HOST="69.62.78.167" \
            -e DB_PORT="5432" \
            -e DB_NAME="doc_db" \
            -e DATABASE_URL="postgresql://postgres:patelyash1234@69.62.78.167:5432/doc_db" \
            -e STRIPE_PUBLIC_KEY="$STRIPE_PUBLIC_KEY" \
            -e STRIPE_SECRET_KEY="$STRIPE_SECRET_KEY" \
            -e STRIPE_WEBHOOK_SECRECT="$STRIPE_WEBHOOK_SECRECT" \
            -e GROQ_API_KEY="$GROQ_API_KEY" \
            -e DJANGO_SUPERUSER_USERNAME="$DJANGO_SUPERUSER_USERNAME" \
            -e DJANGO_SUPERUSER_EMAIL="$DJANGO_SUPERUSER_EMAIL" \
            -e DJANGO_SUPERUSER_PASSWORD="$DJANGO_SUPERUSER_PASSWORD" \
            documentintelligence-django-new
        EOF
      env:
        DB_USER: "postgres"
        DB_PASSWORD: "patelyash1234"
        DB_HOST: "69.62.78.167"
        DB_PORT: "5432"
        DB_NAME: "doc_db"
        DATABASE_URL: "postgresql://postgres:patelyash1234@69.62.78.167:5432/doc_db"

        STRIPE_PUBLIC_KEY: ${{ secrets.STRIPE_PUBLIC_KEY }}
        STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
        STRIPE_WEBHOOK_SECRECT: ${{ secrets.STRIPE_WEBHOOK_SECRECT }}

        DJANGO_SUPERUSER_USERNAME: ${{ secrets.DJANGO_SUPERUSER_USERNAME }}
        DJANGO_SUPERUSER_EMAIL: ${{ secrets.DJANGO_SUPERUSER_EMAIL }}
        DJANGO_SUPERUSER_PASSWORD: ${{ secrets.DJANGO_SUPERUSER_PASSWORD }}

        GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
